name: API Tests with Newman

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest  

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3  

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar Newman e o reporter htmlextra
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Rodar Testes da API com Newman
        run: |
          mkdir -p newman
          newman run collections/postman-collection-test3.json \
            -r cli,json,htmlextra \
            --reporter-json-export ./newman/report.json \
            --reporter-htmlextra-export ./newman/report.html

      - name: Fazer upload do relatório HTML como artefato
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: ./newman/report.html
